package com.zrh.enhance.plugin.web.model;

import java.util.Date;

public class ApplicationManager {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_manager.id
     *
     * @mbggenerated Wed Nov 06 16:46:44 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_manager.application_name
     *
     * @mbggenerated Wed Nov 06 16:46:44 CST 2019
     */
    private String applicationName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_manager.application_ip_address
     *
     * @mbggenerated Wed Nov 06 16:46:44 CST 2019
     */
    private String applicationIpAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_manager.misc_desc
     *
     * @mbggenerated Wed Nov 06 16:46:44 CST 2019
     */
    private String miscDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_manager.status
     *
     * @mbggenerated Wed Nov 06 16:46:44 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_manager.create_time
     *
     * @mbggenerated Wed Nov 06 16:46:44 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_manager.create_oper_id
     *
     * @mbggenerated Wed Nov 06 16:46:44 CST 2019
     */
    private Long createOperId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_manager.create_oper_name
     *
     * @mbggenerated Wed Nov 06 16:46:44 CST 2019
     */
    private String createOperName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_manager.update_time
     *
     * @mbggenerated Wed Nov 06 16:46:44 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_manager.update_oper_id
     *
     * @mbggenerated Wed Nov 06 16:46:44 CST 2019
     */
    private Long updateOperId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_manager.update_oper_name
     *
     * @mbggenerated Wed Nov 06 16:46:44 CST 2019
     */
    private String updateOperName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_manager.id
     *
     * @return the value of application_manager.id
     *
     * @mbggenerated Wed Nov 06 16:46:44 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_manager.id
     *
     * @param id the value for application_manager.id
     *
     * @mbggenerated Wed Nov 06 16:46:44 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_manager.application_name
     *
     * @return the value of application_manager.application_name
     *
     * @mbggenerated Wed Nov 06 16:46:44 CST 2019
     */
    public String getApplicationName() {
        return applicationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_manager.application_name
     *
     * @param applicationName the value for application_manager.application_name
     *
     * @mbggenerated Wed Nov 06 16:46:44 CST 2019
     */
    public void setApplicationName(String applicationName) {
        this.applicationName = applicationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_manager.application_ip_address
     *
     * @return the value of application_manager.application_ip_address
     *
     * @mbggenerated Wed Nov 06 16:46:44 CST 2019
     */
    public String getApplicationIpAddress() {
        return applicationIpAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_manager.application_ip_address
     *
     * @param applicationIpAddress the value for application_manager.application_ip_address
     *
     * @mbggenerated Wed Nov 06 16:46:44 CST 2019
     */
    public void setApplicationIpAddress(String applicationIpAddress) {
        this.applicationIpAddress = applicationIpAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_manager.misc_desc
     *
     * @return the value of application_manager.misc_desc
     *
     * @mbggenerated Wed Nov 06 16:46:44 CST 2019
     */
    public String getMiscDesc() {
        return miscDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_manager.misc_desc
     *
     * @param miscDesc the value for application_manager.misc_desc
     *
     * @mbggenerated Wed Nov 06 16:46:44 CST 2019
     */
    public void setMiscDesc(String miscDesc) {
        this.miscDesc = miscDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_manager.status
     *
     * @return the value of application_manager.status
     *
     * @mbggenerated Wed Nov 06 16:46:44 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_manager.status
     *
     * @param status the value for application_manager.status
     *
     * @mbggenerated Wed Nov 06 16:46:44 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_manager.create_time
     *
     * @return the value of application_manager.create_time
     *
     * @mbggenerated Wed Nov 06 16:46:44 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_manager.create_time
     *
     * @param createTime the value for application_manager.create_time
     *
     * @mbggenerated Wed Nov 06 16:46:44 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_manager.create_oper_id
     *
     * @return the value of application_manager.create_oper_id
     *
     * @mbggenerated Wed Nov 06 16:46:44 CST 2019
     */
    public Long getCreateOperId() {
        return createOperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_manager.create_oper_id
     *
     * @param createOperId the value for application_manager.create_oper_id
     *
     * @mbggenerated Wed Nov 06 16:46:44 CST 2019
     */
    public void setCreateOperId(Long createOperId) {
        this.createOperId = createOperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_manager.create_oper_name
     *
     * @return the value of application_manager.create_oper_name
     *
     * @mbggenerated Wed Nov 06 16:46:44 CST 2019
     */
    public String getCreateOperName() {
        return createOperName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_manager.create_oper_name
     *
     * @param createOperName the value for application_manager.create_oper_name
     *
     * @mbggenerated Wed Nov 06 16:46:44 CST 2019
     */
    public void setCreateOperName(String createOperName) {
        this.createOperName = createOperName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_manager.update_time
     *
     * @return the value of application_manager.update_time
     *
     * @mbggenerated Wed Nov 06 16:46:44 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_manager.update_time
     *
     * @param updateTime the value for application_manager.update_time
     *
     * @mbggenerated Wed Nov 06 16:46:44 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_manager.update_oper_id
     *
     * @return the value of application_manager.update_oper_id
     *
     * @mbggenerated Wed Nov 06 16:46:44 CST 2019
     */
    public Long getUpdateOperId() {
        return updateOperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_manager.update_oper_id
     *
     * @param updateOperId the value for application_manager.update_oper_id
     *
     * @mbggenerated Wed Nov 06 16:46:44 CST 2019
     */
    public void setUpdateOperId(Long updateOperId) {
        this.updateOperId = updateOperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_manager.update_oper_name
     *
     * @return the value of application_manager.update_oper_name
     *
     * @mbggenerated Wed Nov 06 16:46:44 CST 2019
     */
    public String getUpdateOperName() {
        return updateOperName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_manager.update_oper_name
     *
     * @param updateOperName the value for application_manager.update_oper_name
     *
     * @mbggenerated Wed Nov 06 16:46:44 CST 2019
     */
    public void setUpdateOperName(String updateOperName) {
        this.updateOperName = updateOperName;
    }
}