package com.zrh.enhance.plugin.web.model;

import java.util.Date;

public class ApplicationPluginManager {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_plugin_manager.id
     *
     * @mbggenerated Mon Nov 11 09:20:48 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_plugin_manager.application_id
     *
     * @mbggenerated Mon Nov 11 09:20:48 CST 2019
     */
    private Long applicationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_plugin_manager.plugin_id
     *
     * @mbggenerated Mon Nov 11 09:20:48 CST 2019
     */
    private Long pluginId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_plugin_manager.install_status
     *
     * @mbggenerated Mon Nov 11 09:20:48 CST 2019
     */
    private Integer installStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_plugin_manager.active_status
     *
     * @mbggenerated Mon Nov 11 09:20:48 CST 2019
     */
    private Integer activeStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_plugin_manager.misc_desc
     *
     * @mbggenerated Mon Nov 11 09:20:48 CST 2019
     */
    private String miscDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_plugin_manager.status
     *
     * @mbggenerated Mon Nov 11 09:20:48 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_plugin_manager.create_time
     *
     * @mbggenerated Mon Nov 11 09:20:48 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_plugin_manager.create_oper_id
     *
     * @mbggenerated Mon Nov 11 09:20:48 CST 2019
     */
    private Long createOperId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_plugin_manager.create_oper_name
     *
     * @mbggenerated Mon Nov 11 09:20:48 CST 2019
     */
    private String createOperName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_plugin_manager.update_time
     *
     * @mbggenerated Mon Nov 11 09:20:48 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_plugin_manager.update_oper_id
     *
     * @mbggenerated Mon Nov 11 09:20:48 CST 2019
     */
    private Long updateOperId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_plugin_manager.update_oper_name
     *
     * @mbggenerated Mon Nov 11 09:20:48 CST 2019
     */
    private String updateOperName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_plugin_manager.id
     *
     * @return the value of application_plugin_manager.id
     *
     * @mbggenerated Mon Nov 11 09:20:48 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_plugin_manager.id
     *
     * @param id the value for application_plugin_manager.id
     *
     * @mbggenerated Mon Nov 11 09:20:48 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_plugin_manager.application_id
     *
     * @return the value of application_plugin_manager.application_id
     *
     * @mbggenerated Mon Nov 11 09:20:48 CST 2019
     */
    public Long getApplicationId() {
        return applicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_plugin_manager.application_id
     *
     * @param applicationId the value for application_plugin_manager.application_id
     *
     * @mbggenerated Mon Nov 11 09:20:48 CST 2019
     */
    public void setApplicationId(Long applicationId) {
        this.applicationId = applicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_plugin_manager.plugin_id
     *
     * @return the value of application_plugin_manager.plugin_id
     *
     * @mbggenerated Mon Nov 11 09:20:48 CST 2019
     */
    public Long getPluginId() {
        return pluginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_plugin_manager.plugin_id
     *
     * @param pluginId the value for application_plugin_manager.plugin_id
     *
     * @mbggenerated Mon Nov 11 09:20:48 CST 2019
     */
    public void setPluginId(Long pluginId) {
        this.pluginId = pluginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_plugin_manager.install_status
     *
     * @return the value of application_plugin_manager.install_status
     *
     * @mbggenerated Mon Nov 11 09:20:48 CST 2019
     */
    public Integer getInstallStatus() {
        return installStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_plugin_manager.install_status
     *
     * @param installStatus the value for application_plugin_manager.install_status
     *
     * @mbggenerated Mon Nov 11 09:20:48 CST 2019
     */
    public void setInstallStatus(Integer installStatus) {
        this.installStatus = installStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_plugin_manager.active_status
     *
     * @return the value of application_plugin_manager.active_status
     *
     * @mbggenerated Mon Nov 11 09:20:48 CST 2019
     */
    public Integer getActiveStatus() {
        return activeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_plugin_manager.active_status
     *
     * @param activeStatus the value for application_plugin_manager.active_status
     *
     * @mbggenerated Mon Nov 11 09:20:48 CST 2019
     */
    public void setActiveStatus(Integer activeStatus) {
        this.activeStatus = activeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_plugin_manager.misc_desc
     *
     * @return the value of application_plugin_manager.misc_desc
     *
     * @mbggenerated Mon Nov 11 09:20:48 CST 2019
     */
    public String getMiscDesc() {
        return miscDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_plugin_manager.misc_desc
     *
     * @param miscDesc the value for application_plugin_manager.misc_desc
     *
     * @mbggenerated Mon Nov 11 09:20:48 CST 2019
     */
    public void setMiscDesc(String miscDesc) {
        this.miscDesc = miscDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_plugin_manager.status
     *
     * @return the value of application_plugin_manager.status
     *
     * @mbggenerated Mon Nov 11 09:20:48 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_plugin_manager.status
     *
     * @param status the value for application_plugin_manager.status
     *
     * @mbggenerated Mon Nov 11 09:20:48 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_plugin_manager.create_time
     *
     * @return the value of application_plugin_manager.create_time
     *
     * @mbggenerated Mon Nov 11 09:20:48 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_plugin_manager.create_time
     *
     * @param createTime the value for application_plugin_manager.create_time
     *
     * @mbggenerated Mon Nov 11 09:20:48 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_plugin_manager.create_oper_id
     *
     * @return the value of application_plugin_manager.create_oper_id
     *
     * @mbggenerated Mon Nov 11 09:20:48 CST 2019
     */
    public Long getCreateOperId() {
        return createOperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_plugin_manager.create_oper_id
     *
     * @param createOperId the value for application_plugin_manager.create_oper_id
     *
     * @mbggenerated Mon Nov 11 09:20:48 CST 2019
     */
    public void setCreateOperId(Long createOperId) {
        this.createOperId = createOperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_plugin_manager.create_oper_name
     *
     * @return the value of application_plugin_manager.create_oper_name
     *
     * @mbggenerated Mon Nov 11 09:20:48 CST 2019
     */
    public String getCreateOperName() {
        return createOperName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_plugin_manager.create_oper_name
     *
     * @param createOperName the value for application_plugin_manager.create_oper_name
     *
     * @mbggenerated Mon Nov 11 09:20:48 CST 2019
     */
    public void setCreateOperName(String createOperName) {
        this.createOperName = createOperName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_plugin_manager.update_time
     *
     * @return the value of application_plugin_manager.update_time
     *
     * @mbggenerated Mon Nov 11 09:20:48 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_plugin_manager.update_time
     *
     * @param updateTime the value for application_plugin_manager.update_time
     *
     * @mbggenerated Mon Nov 11 09:20:48 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_plugin_manager.update_oper_id
     *
     * @return the value of application_plugin_manager.update_oper_id
     *
     * @mbggenerated Mon Nov 11 09:20:48 CST 2019
     */
    public Long getUpdateOperId() {
        return updateOperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_plugin_manager.update_oper_id
     *
     * @param updateOperId the value for application_plugin_manager.update_oper_id
     *
     * @mbggenerated Mon Nov 11 09:20:48 CST 2019
     */
    public void setUpdateOperId(Long updateOperId) {
        this.updateOperId = updateOperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_plugin_manager.update_oper_name
     *
     * @return the value of application_plugin_manager.update_oper_name
     *
     * @mbggenerated Mon Nov 11 09:20:48 CST 2019
     */
    public String getUpdateOperName() {
        return updateOperName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_plugin_manager.update_oper_name
     *
     * @param updateOperName the value for application_plugin_manager.update_oper_name
     *
     * @mbggenerated Mon Nov 11 09:20:48 CST 2019
     */
    public void setUpdateOperName(String updateOperName) {
        this.updateOperName = updateOperName;
    }
}