package com.zrh.enhance.plugin.web.model;

import java.util.Date;

public class PluginInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugin_info.id
     *
     * @mbggenerated Sat Nov 09 09:14:51 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugin_info.name
     *
     * @mbggenerated Sat Nov 09 09:14:51 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugin_info.class_name
     *
     * @mbggenerated Sat Nov 09 09:14:51 CST 2019
     */
    private String className;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugin_info.version
     *
     * @mbggenerated Sat Nov 09 09:14:51 CST 2019
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugin_info.jar_remote_Url
     *
     * @mbggenerated Sat Nov 09 09:14:51 CST 2019
     */
    private String jarRemoteUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugin_info.misc_desc
     *
     * @mbggenerated Sat Nov 09 09:14:51 CST 2019
     */
    private String miscDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugin_info.status
     *
     * @mbggenerated Sat Nov 09 09:14:51 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugin_info.create_time
     *
     * @mbggenerated Sat Nov 09 09:14:51 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugin_info.create_oper_id
     *
     * @mbggenerated Sat Nov 09 09:14:51 CST 2019
     */
    private Long createOperId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugin_info.create_oper_name
     *
     * @mbggenerated Sat Nov 09 09:14:51 CST 2019
     */
    private String createOperName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugin_info.update_time
     *
     * @mbggenerated Sat Nov 09 09:14:51 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugin_info.update_oper_id
     *
     * @mbggenerated Sat Nov 09 09:14:51 CST 2019
     */
    private Long updateOperId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugin_info.update_oper_name
     *
     * @mbggenerated Sat Nov 09 09:14:51 CST 2019
     */
    private String updateOperName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugin_info.id
     *
     * @return the value of plugin_info.id
     *
     * @mbggenerated Sat Nov 09 09:14:51 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugin_info.id
     *
     * @param id the value for plugin_info.id
     *
     * @mbggenerated Sat Nov 09 09:14:51 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugin_info.name
     *
     * @return the value of plugin_info.name
     *
     * @mbggenerated Sat Nov 09 09:14:51 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugin_info.name
     *
     * @param name the value for plugin_info.name
     *
     * @mbggenerated Sat Nov 09 09:14:51 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugin_info.class_name
     *
     * @return the value of plugin_info.class_name
     *
     * @mbggenerated Sat Nov 09 09:14:51 CST 2019
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugin_info.class_name
     *
     * @param className the value for plugin_info.class_name
     *
     * @mbggenerated Sat Nov 09 09:14:51 CST 2019
     */
    public void setClassName(String className) {
        this.className = className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugin_info.version
     *
     * @return the value of plugin_info.version
     *
     * @mbggenerated Sat Nov 09 09:14:51 CST 2019
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugin_info.version
     *
     * @param version the value for plugin_info.version
     *
     * @mbggenerated Sat Nov 09 09:14:51 CST 2019
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugin_info.jar_remote_Url
     *
     * @return the value of plugin_info.jar_remote_Url
     *
     * @mbggenerated Sat Nov 09 09:14:51 CST 2019
     */
    public String getJarRemoteUrl() {
        return jarRemoteUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugin_info.jar_remote_Url
     *
     * @param jarRemoteUrl the value for plugin_info.jar_remote_Url
     *
     * @mbggenerated Sat Nov 09 09:14:51 CST 2019
     */
    public void setJarRemoteUrl(String jarRemoteUrl) {
        this.jarRemoteUrl = jarRemoteUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugin_info.misc_desc
     *
     * @return the value of plugin_info.misc_desc
     *
     * @mbggenerated Sat Nov 09 09:14:51 CST 2019
     */
    public String getMiscDesc() {
        return miscDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugin_info.misc_desc
     *
     * @param miscDesc the value for plugin_info.misc_desc
     *
     * @mbggenerated Sat Nov 09 09:14:51 CST 2019
     */
    public void setMiscDesc(String miscDesc) {
        this.miscDesc = miscDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugin_info.status
     *
     * @return the value of plugin_info.status
     *
     * @mbggenerated Sat Nov 09 09:14:51 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugin_info.status
     *
     * @param status the value for plugin_info.status
     *
     * @mbggenerated Sat Nov 09 09:14:51 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugin_info.create_time
     *
     * @return the value of plugin_info.create_time
     *
     * @mbggenerated Sat Nov 09 09:14:51 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugin_info.create_time
     *
     * @param createTime the value for plugin_info.create_time
     *
     * @mbggenerated Sat Nov 09 09:14:51 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugin_info.create_oper_id
     *
     * @return the value of plugin_info.create_oper_id
     *
     * @mbggenerated Sat Nov 09 09:14:51 CST 2019
     */
    public Long getCreateOperId() {
        return createOperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugin_info.create_oper_id
     *
     * @param createOperId the value for plugin_info.create_oper_id
     *
     * @mbggenerated Sat Nov 09 09:14:51 CST 2019
     */
    public void setCreateOperId(Long createOperId) {
        this.createOperId = createOperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugin_info.create_oper_name
     *
     * @return the value of plugin_info.create_oper_name
     *
     * @mbggenerated Sat Nov 09 09:14:51 CST 2019
     */
    public String getCreateOperName() {
        return createOperName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugin_info.create_oper_name
     *
     * @param createOperName the value for plugin_info.create_oper_name
     *
     * @mbggenerated Sat Nov 09 09:14:51 CST 2019
     */
    public void setCreateOperName(String createOperName) {
        this.createOperName = createOperName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugin_info.update_time
     *
     * @return the value of plugin_info.update_time
     *
     * @mbggenerated Sat Nov 09 09:14:51 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugin_info.update_time
     *
     * @param updateTime the value for plugin_info.update_time
     *
     * @mbggenerated Sat Nov 09 09:14:51 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugin_info.update_oper_id
     *
     * @return the value of plugin_info.update_oper_id
     *
     * @mbggenerated Sat Nov 09 09:14:51 CST 2019
     */
    public Long getUpdateOperId() {
        return updateOperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugin_info.update_oper_id
     *
     * @param updateOperId the value for plugin_info.update_oper_id
     *
     * @mbggenerated Sat Nov 09 09:14:51 CST 2019
     */
    public void setUpdateOperId(Long updateOperId) {
        this.updateOperId = updateOperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugin_info.update_oper_name
     *
     * @return the value of plugin_info.update_oper_name
     *
     * @mbggenerated Sat Nov 09 09:14:51 CST 2019
     */
    public String getUpdateOperName() {
        return updateOperName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugin_info.update_oper_name
     *
     * @param updateOperName the value for plugin_info.update_oper_name
     *
     * @mbggenerated Sat Nov 09 09:14:51 CST 2019
     */
    public void setUpdateOperName(String updateOperName) {
        this.updateOperName = updateOperName;
    }
}