package com.zrh.enhance.plugin.web.dao;

import com.zrh.enhance.plugin.web.dto.ApplicationPluginDTO;
import com.zrh.enhance.plugin.web.model.ApplicationPluginManager;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ApplicationPluginManagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_plugin_manager
     *
     * @mbggenerated Mon Nov 11 09:20:48 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_plugin_manager
     *
     * @mbggenerated Mon Nov 11 09:20:48 CST 2019
     */
    int insert(ApplicationPluginManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_plugin_manager
     *
     * @mbggenerated Mon Nov 11 09:20:48 CST 2019
     */
    int insertSelective(ApplicationPluginManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_plugin_manager
     *
     * @mbggenerated Mon Nov 11 09:20:48 CST 2019
     */
    ApplicationPluginManager selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_plugin_manager
     *
     * @mbggenerated Mon Nov 11 09:20:48 CST 2019
     */
    int updateByPrimaryKeySelective(ApplicationPluginManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_plugin_manager
     *
     * @mbggenerated Mon Nov 11 09:20:48 CST 2019
     */
    int updateByPrimaryKey(ApplicationPluginManager record);


    ApplicationPluginManager selectByApplicationIdAndPluginId(@Param("applicationId") Long applicationId, @Param("pluginId")  Long pluginId);

    List<ApplicationPluginDTO> selectApplicationPluginList(Long applicationId);

}