package com.zrh.enhance.plugin.web.dao;

import com.zrh.enhance.plugin.web.model.ApplicationManager;

import java.util.List;

public interface ApplicationManagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_manager
     *
     * @mbggenerated Wed Nov 06 16:46:44 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_manager
     *
     * @mbggenerated Wed Nov 06 16:46:44 CST 2019
     */
    int insert(ApplicationManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_manager
     *
     * @mbggenerated Wed Nov 06 16:46:44 CST 2019
     */
    int insertSelective(ApplicationManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_manager
     *
     * @mbggenerated Wed Nov 06 16:46:44 CST 2019
     */
    ApplicationManager selectByPrimaryKey(Long id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_manager
     *
     * @mbggenerated Wed Nov 06 16:46:44 CST 2019
     */
    int updateByPrimaryKeySelective(ApplicationManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_manager
     *
     * @mbggenerated Wed Nov 06 16:46:44 CST 2019
     */
    int updateByPrimaryKey(ApplicationManager record);

    ApplicationManager selectByApplicationAddress(String applicationAddress);

    List<ApplicationManager> selectList();
}